// <auto-generated />
using System;
using ExpenditureTrackerWeb.Shared.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenditureTrackerWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241025155354_mssql.onprem_migration_955")]
    partial class mssqlonprem_migration_955
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenditureTrackerWeb.Shared.Entities.Expense", b =>
                {
                    b.Property<int>("EX_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EX_Id"));

                    b.Property<decimal>("EX_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EX_DateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("EX_Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("EX_TransactionCategoryTC_Id")
                        .HasColumnType("int");

                    b.Property<int>("EX_UserU_Id")
                        .HasColumnType("int");

                    b.HasKey("EX_Id");

                    b.HasIndex("EX_TransactionCategoryTC_Id");

                    b.HasIndex("EX_UserU_Id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ExpenditureTrackerWeb.Shared.Entities.TransactionCategory", b =>
                {
                    b.Property<int>("TC_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TC_Id"));

                    b.Property<string>("TC_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TC_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TC_TransactionTypeTT_Id")
                        .HasColumnType("int");

                    b.Property<int>("TC_UserU_Id")
                        .HasColumnType("int");

                    b.HasKey("TC_Id");

                    b.HasIndex("TC_TransactionTypeTT_Id");

                    b.HasIndex("TC_UserU_Id");

                    b.ToTable("TransactionCategories");
                });

            modelBuilder.Entity("ExpenditureTrackerWeb.Shared.Entities.TransactionType", b =>
                {
                    b.Property<int>("TT_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TT_Id"));

                    b.Property<string>("TT_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TT_Id");

                    b.ToTable("TransactionTypes");
                });

            modelBuilder.Entity("ExpenditureTrackerWeb.Shared.Models.User", b =>
                {
                    b.Property<int>("U_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("U_Id"));

                    b.Property<string>("U_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("U_FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("U_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("U_Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("U_Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExpenditureTrackerWeb.Shared.Entities.Expense", b =>
                {
                    b.HasOne("ExpenditureTrackerWeb.Shared.Entities.TransactionCategory", "EX_TransactionCategory")
                        .WithMany("TC_Expenses")
                        .HasForeignKey("EX_TransactionCategoryTC_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenditureTrackerWeb.Shared.Models.User", "EX_User")
                        .WithMany("U_Expense")
                        .HasForeignKey("EX_UserU_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EX_TransactionCategory");

                    b.Navigation("EX_User");
                });

            modelBuilder.Entity("ExpenditureTrackerWeb.Shared.Entities.TransactionCategory", b =>
                {
                    b.HasOne("ExpenditureTrackerWeb.Shared.Entities.TransactionType", "TC_TransactionType")
                        .WithMany("TT_TransactionCategories")
                        .HasForeignKey("TC_TransactionTypeTT_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenditureTrackerWeb.Shared.Models.User", "TC_User")
                        .WithMany("U_TransactionCategories")
                        .HasForeignKey("TC_UserU_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TC_TransactionType");

                    b.Navigation("TC_User");
                });

            modelBuilder.Entity("ExpenditureTrackerWeb.Shared.Entities.TransactionCategory", b =>
                {
                    b.Navigation("TC_Expenses");
                });

            modelBuilder.Entity("ExpenditureTrackerWeb.Shared.Entities.TransactionType", b =>
                {
                    b.Navigation("TT_TransactionCategories");
                });

            modelBuilder.Entity("ExpenditureTrackerWeb.Shared.Models.User", b =>
                {
                    b.Navigation("U_Expense");

                    b.Navigation("U_TransactionCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
